INSERT INTO USERS (USER_ID, PASSWORD, NICKNAME, NAME, EMAIL, PHONE_NUMBER, ROLE_TYPE, ENABLED, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES
(1, 'user', '일반사용자닉', '일반이름', 'test@gmail1.com', '01012341234', 'USER', 'Y', CURRENT_TIMESTAMP , 0, CURRENT_TIMESTAMP, 0),
(2, 'admin', '관리자사용자닉', '관리자이름', 'admin@gmail1.com', '01043214321', 'ADMIN', 'Y', CURRENT_TIMESTAMP , 0, CURRENT_TIMESTAMP, 0);